### ISSUE TITLE
Custom cards

### ISSUE THREAD

**Issue by dannymertens** [thomasloven/lovelace-hui-element#1]
Hi Thomas,

Great card as always, thanks!
Is it also possible to add a custom card type like for instance Mini Graph Card and/or Mini Media Player?
I tried it but don't get it to work?

![image](https://user-images.githubusercontent.com/46963011/79759839-7b0e9700-831f-11ea-9c74-c2aaa567aa85.png)

```
cards:
  - cards:
      - entities:
          - entity: sensor.wasruimte_motion_temperature
            type: 'custom:multiple-entity-row'
            name: Wasruimte
            state_color: true
            state_header: Temp
            entities:
              - entity: sensor.temp_diepvries_temperatuur
                name: DV Temp
              - entity: sensor.temp_diepvries_luchtvochtigheid
                name: DV Lucht
              - entity: binary_sensor.water_wasruimte_sabotagealarm
                name: water alarm
          - type: 'custom:hui-element'
            card_type: glance
            entities:
              - entity: sensor.hue_dimmer_wasruimte_accuniveau
                name: Hue dimmer
              - entity: sensor.water_wasruimte_accuniveau
                name: Water sensor
              - entity: sensor.temp_diepvries_accuniveau
                name: Diepvries
              - entity: sensor.achterdeur_accuniveau
                name: Achterdeur
          - type: 'custom:hui-element'
            card_type: glance
            entities:
              - entity: binary_sensor.wasmachine_deur_geopend
                name: WM open
              - entity: sensor.wasmachine_resterende_tijd
                name: WM Res tijd
              - entity: binary_sensor.droger_deur_geopend
                name: DK Open
              - entity: sensor.droger_resterende_tijd
                name: DK Res tijd
          - type: 'custom:hui-element'
            card_type: history-graph
            entities:
              - entity: sensor.wasruimte_motion_light_level
                hours_to_show: 24
                name: Lichtniveau
                refresh_interval: 0
        type: entities
    type: vertical-stack
parameters:
  scrollbar:
    draggable: true
    hide: false
    snapOnRelease: true
  spaceBetween: 8
type: 'custom:swipe-card'
```

**Comment by thomasloven** [comment]
*Where* did you try it?
*How* did you try it?
The example you provided doesn't contain a single trace of even "`mini`". How did you expect **that** to work?

However, for custom cards/rows/entities you don't need hui-element. Just specify it as usual.

**Comment by dannymertens** [comment]
> _Where_ did you try it?
> _How_ did you try it?
> The example you provided doesn't contain a single trace of even "`mini`". How did you expect **that** to work?
> 
> However, for custom cards/rows/entities you don't need hui-element. Just specify it as usual.
> 
> Edit: I really do appreciate that you included both a screenshot and a code snippet to indicate where you tried to use hui-element and in what context, but including the error and what causes it would have been more useful for the next time :)

Oops sorry @thomasloven  forgot to paste the code that I tried :-( I know it probably has something to do again with yaml ;-) but for some reason that stays difficult for me :-P 

I wanted to add a custom:mini-graph-card on the bottom of the card as a replacement for the standard history graph because I have more configurable options with that card

```
cards:
  - cards:
      - entities:
          - entities:
              - entity: sensor.temp_diepvries_temperatuur
                name: DV Temp
              - entity: sensor.temp_diepvries_luchtvochtigheid
                name: DV Lucht
              - entity: binary_sensor.water_wasruimte_sabotagealarm
                name: water alarm
            entity: sensor.wasruimte_motion_temperature
            name: Wasruimte
            state_color: true
            state_header: Temp
            type: 'custom:multiple-entity-row'
          - card_type: glance
            entities:
              - entity: sensor.hue_dimmer_wasruimte_accuniveau
                name: Hue dimmer
              - entity: sensor.water_wasruimte_accuniveau
                name: Water sensor
              - entity: sensor.temp_diepvries_accuniveau
                name: Diepvries
              - entity: sensor.achterdeur_accuniveau
                name: Achterdeur
            type: 'custom:hui-element'
          - card_type: glance
            entities:
              - entity: binary_sensor.wasmachine_deur_geopend
                name: WM open
              - entity: sensor.wasmachine_resterende_tijd
                name: WM Res tijd
              - entity: binary_sensor.droger_deur_geopend
                name: DK Open
              - entity: sensor.droger_resterende_tijd
                name: DK Res tijd
            type: 'custom:hui-element'
          - card_type: history-graph
            entities:
              - card_type: 'custom:mini-graph-card'
                entities:
                - entity: sensor.wasruimte_motion_light_level
                    name: Wasruimte
                    show_state: true
                    state_adaptive_color: true
                - entity: sensor.dressing_beweging_helderheid
                    name: Dressing
                    show_state: true
                    state_adaptive_color: true
                - entity: sensor.motion_nachthal_light_level
                    name: Nachthal
                    show_state: true
                    state_adaptive_color: true
                - entity: sensor.bureau_light_level
                    name: Bureau
                    show_fill: false
                    show_state: false
                    state_adaptive_color: true
                - entity: sensor.badkamer_sensor_light_level
                    name: Badkamer
                    show_fill: false
                    show_state: false
                    state_adaptive_color: true
                height: 100
                hour24: true
                hours_to_show: 24
                line_width: 2
                name: Licht niveau
                points_per_hour: 20
            type: 'custom:hui-element'
        type: entities
    type: vertical-stack
parameters:
  scrollbar:
    draggable: true
    hide: false
    snapOnRelease: true
  spaceBetween: 8
type: 'custom:swipe-card'
```

**Comment by thomasloven** [comment]
It helps me to thing of yaml as little blocks. The block you want to change is the last card in the list - this one:
```yaml
          - type: 'custom:hui-element'
            card_type: history-graph
            entities:
              - entity: sensor.wasruimte_motion_light_level
                hours_to_show: 24
                name: Lichtniveau
                refresh_interval: 0
```

> Pro tip: What I call a "block" in this case is delimited by the indentation - the distance from left to the first character on each line. A new block begins wherever there's more spaces in the start than at the line before, and continues until there are fewer spaces in the next line. Thus a "block" can contain more "blocks" inside it.

The first dash is part of the structure for the list of entities for the card you've put this inside, so we can ignore that and then lift this out into it's own card:

```yaml
type: 'custom:hui-element'
card_type: history-graph
entities:
  - entity: sensor.wasruimte_motion_light_level
    hours_to_show: 24
    name: Lichtniveau
    refresh_interval: 0
```

It could probably help to actually do that. Pull that out and put it inside its own card.
Then you change it to be a `custom:mini-graph-card` instead of a `history-graph` card, by replacing `card_type: history-graph` with `card_type: custom:mini-graph-card` and apply any configuration changes you want (as per the mini-graph-card documentation - I'm not a user myself, so I will leave that part out...).

You'll be left with something like:
```yaml
type: custom:hui-element
card_type: custom:mini-graph-card
entites:
  - ... some stuff here...
height: 100
hours_to_show: 24
... etc ...
```

After making sure this works as a stand-alone card, you can copy everything and bring it back into the big picture, by replacing the block you pulled out *entirely* (and adding back the dash and adding the necessary indentation of course.

You're not making it easy for yourself by wrapping cards in cards in cards, but that's part of the power of lovelace. Always make sure small parts work by them selves before trying to combine them - Divide and Conquer.
