### ISSUE TITLE
Can't add css to main element with last update

### ISSUE THREAD

**Issue by griZouw** [thomasloven/lovelace-hui-element#14]
Hello,

Since last update, i can't add css to :host anymore. I was adding it with card mod.

Here is my template, maybe it can helps
```yaml
  type: 'custom:hui-element'
  card_type: vertical-stack
  cards: 
  ----------
  card_mod:
    style: >
      :host { transform: unset !important; position: fixed; left: 1442px; top: 0px; height: 1080px; padding: 0px 50px 50px 50px; width: 378px; }
```

(And thx for your amazing work dude)

**Comment by ildar170975** [comment]
Thomas, is my case related to this?
```
      - type: picture-elements
        elements:
          - type: custom:hui-element
            row_type: toggle-entity
            entity: input_boolean.test_boolean
            name: Colored
            style:
              top: 42%
              left: 0%
              transform: translate(0,0)
              width: 250px
            card_mod: |
              :host {
                color: red;
              }
        image: /local/images/white.jpg
```
Since ~2021.10 any styles for `hui-element` inside `picture-elements` stopped working.

**Comment by thomasloven** [comment]
```yaml
card_mod: |
```
is not correct at all.

If your problem is related to this, I believe it should be fixed in the latest update.

**Comment by ildar170975** [comment]
> is not correct at all.

Sorry, that was a typo, the original style was a bit different, made a typo while copying the code to the Github.
The code is:
```
        card_mod:
          styles: |
            :host {
              color: red;
            }
```
The color is not changed.

**Comment by ildar170975** [comment]
Also, there is a similar problem with `hui-element` - cannot apply styles (observed for `picture-elements` & `entities` cards), earlier it worked - see the example for `entities` card below:
```
type: entities
entities:
  - type: custom:hui-element
    row_type: sensor-entity
    entity: sun.sun
    name: Colored
    card_mod:
      style:
        hui-sensor-entity-row:
          $:
            hui-generic-entity-row:
              $: |
                .info {
                  color: red;
                }
  - type: custom:hui-element
    row_type: sensor-entity
    entity: sun.sun
    name: Colored
    card_mod:
      style: |
        hui-sensor-entity-row {
          color: red;
        }
  - type: custom:hui-element
    row_type: sensor-entity
    entity: sun.sun
    name: Colored
    card_mod:
      style: |
        :host {
          color: red;
        }
```
![image](https://user-images.githubusercontent.com/71872483/141019323-f3de8034-9742-4c54-b33c-e4158a3d591b.png)

Is it a related problem? Shall I register a separate issue?

**Comment by thomasloven** [comment]
The style is now started at the actual element (hui-sensor-entity-row), like it should have been from the start.
If it worked before, that was actually a bug - though an obscure one.
Try
```yaml
card_mod:
      style:
          $:
            hui-generic-entity-row:
              $: |
                .info {
                  color: red;
                }
```

**Comment by ildar170975** [comment]
```
style:
          $:
            hui-generic-entity-row:
```
Great, it works!

I have never seen this construction. I believed that it always must be smth like:
```
style:
  some_element:
    $:
      next_element:
         ...
```
Now I realized that the 1st element may be missing)))
