### ISSUE TITLE
Change entity name not work with Glance card

### ISSUE THREAD

**Issue by 0r1g1ne** [thomasloven/lovelace-hui-element#18]
Hello,
I use hui-element with glance card-type and i try force entity's name but it's not work.
The state continue to be display. It's a binary sensor and the glance display "on" instead of the text forced in my card with "name:" of entity.

my code
```yaml
          - type: custom:hui-element
              card_type: glance
              show_name: false                                   ---------------------------> if true, show the original name above the icon
              entities:
                - entity: sensor.temperature_exterieur
                  icon: mdi:cloud
                - entity: input_number.chauffage_salon_consigne
                  icon: mdi:target
                - entity: switch.schedule_chauffage_salon_auto_confort
                  icon: mdi:calendar-week
                  name: Confort                                    ------------------------------> ignore
                - entity: switch.schedule_chauffage_planif_auto_eco
                  icon: mdi:calendar-weekend  
                  name: Eco                                          ------------------------------> ignore
```                                       

Thanks for help.
