### ISSUE TITLE
card-mod on picture-elements to style inside a hui-element markdown card.

### ISSUE THREAD

**Issue by matt8707** [thomasloven/lovelace-hui-element#5]
I'm having issues with styling inside a hui-element markdown card. Since it works sporadically maybe it's a timing issue, the markdown card loads before card-mod. Would love to have you look into it when you have time. 

```
title: Hemma
views:
  - panel: true
    path: default_view
    cards:
      - type: picture-elements
        image: /local/background.png
        style:
          "#root > hui-element > hui-markdown-card":
            $:
              "ha-card > ha-markdown":
                $: |
                  ha-markdown-element > p > span {font-size: 2vw; color: red;}

        elements:
          - type: custom:hui-element
            card_type: markdown
            style:
              {top: 50%, left: 50%, width: 20vw}
            content: >
              <span>css styled text</span>

              other text
```

### Editing lovelace and updating dashboard works

![style](https://user-images.githubusercontent.com/36163594/87253894-22165100-c47f-11ea-8fe3-6085d0c234fe.png)

### Refreshing the page after that seems to only load the style sometimes

![no](https://user-images.githubusercontent.com/36163594/87253897-26db0500-c47f-11ea-8419-b7028ac25f6a.png)

I'm currently using [lovelace-card-preloader](https://github.com/gadgetchnnel/lovelace-card-preloader/) which has the reverse issue. Doesn't work on first refresh after editing lovelace, but works after that so the styling is correct.
