### ISSUE TITLE
card_type: light gives an error

### ISSUE THREAD

**Issue by Milithor** [thomasloven/lovelace-hui-element#7]
Error: "Specify an entity from within the light domain." seen when using following code:
```
type: entities
entities:
  - light.eetkamer
  - type: 'custom:hui-element'
    card_type: light
    entities:
      - light.ambiance_commode
      - light.ambiance_eetkamer_2
```
Works fine if the "glance" type is chosen.

**Comment by thomasloven** [comment]
https://www.home-assistant.io/lovelace/light/

**Comment by Milithor** [comment]
Have you actually read this?
I have had a look already on that lovelace light card, but can't seem to figure out what the error is about.

**Comment by thomasloven** [comment]
[I have](https://www.home-assistant.io/lovelace/light/#entity).

As a general tip; if something doesn't work, start by picking it apart and getting it to work one piece at a time.
For example: in your case, does the following work if you try it as a standalone card?

```yaml
type: light
entities:
  - light.ambiance_commode
  - light.ambiance_eetkamer_2
```
