### ISSUE TITLE
Can I place a graph (sensor or history card) card in a picture-elements card with this?

### ISSUE THREAD

**Issue by fribse** [thomasloven/lovelace-hui-element#8]
I currently have this setup:

```
elements:
  - entity: sensor.pool_temperature
    style:
      color: white
      font-size: 1.1em
      left: 50%
      top: 48%
    type: state-label
  - entity: sensor.netatmo_greve_have_temperature
    style:
      font-size: 1.5em
      left: 80%
      top: 4%
    type: state-label
  - entity: sensor.yr_current_symbol
    style:
      left: 66%
      top: 6%
    type: state-icon
  - entity: sensor.gardendistributor_power
    style:
      font-size: 1.3em
      left: 80%
      top: 74%
    type: state-label
  - entity: switch.poolpump
    state_image:
      'off': /local/images/water-flow-cropped-still.gif
      'on': /local/images/water-flow-cropped.gif
    style:
      left: 50%
      top: 74%
      width: 30%
    tap_action:
      action: toggle
    type: image
image: /local/images/pool-pictogram3.png
title: Pool
type: picture-elements
```

That looks like this in lovelace:
![image](https://user-images.githubusercontent.com/13660621/89527549-c8891400-d7e9-11ea-91eb-24bf5ba14110.png)

I would like to display a temperature graph in the 'water', so I was thinking I could somehow get the sensor or history card added as a hui-custom, and then place it and modify it with card-mod.

**Comment by fribse** [comment]
I still can't get this to work.

My test card looks like this now:
`elements:
  - entity: sensor.pool_temperature
    style:
      color: white
      font-size: 2em
      left: 60%
      top: 40%
    type: state-label
  - entity: sensor.netatmo_greve_kokken_have_temperature
    style:
      font-size: 1.5em
      left: 85%
      top: 4%
    type: state-label
  - entity: sensor.gardendistributor_power
    style:
      font-size: 1.3em
      left: 90%
      top: 74%
    type: state-label
  - entity: switch.poolpump
    state_image:
      'off': /local/images/water-flow-cropped-still.gif
      'on': /local/images/water-flow-cropped.gif
    style:
      left: 60%
      top: 74%
      width: 30%
    tap_action:
      action: toggle
    type: image
  - entity: binary_sensor.water_too_low
    title: Water level
    style:
      font-size: 1.3em
      left: 11%
      top: 42%
    type: state-icon
  - entity: binary_sensor.water_too_high
    style:
      font-size: 1.3em
      left: 11%
      top: 22%
    type: state-icon
  - entity: custom:hui-element
    card_type: sensor
    detail: 2
    entity: sensor.pool_temperature
    graph: line
    style:
      left: 30%
      top: 40%
image: /local/images/pool-pictogram4.png
title: Pool
type: picture-elements
`

But I get this shown:
![image](https://user-images.githubusercontent.com/13660621/127469144-4ea5da62-469e-45e4-bec2-5a7aa3555799.png)

I don't understand that message? No card type? How about the card_type I wrote?

**Comment by fribse** [comment]
Ok, I got a bit further with this (finally had some time to do it)

```
elements:
  - entity: sensor.netatmo_greve_kokken_have_temperature
    style:
      font-size: 1.5em
      left: 85%
      top: 4%
    type: state-label
  - entity: sensor.gardendistributor_power
    style:
      font-size: 1.3em
      left: 90%
      top: 74%
    type: state-label
  - entity: switch.poolpump
    state_image:
      'off': /local/images/water-flow-cropped-still.gif
      'on': /local/images/water-flow-cropped.gif
    style:
      left: 60%
      top: 74%
      width: 30%
    tap_action:
      action: toggle
    type: image
  - entity: binary_sensor.water_too_low
    title: Water level
    style:
      font-size: 1.3em
      left: 11%
      top: 42%
    type: state-icon
  - entity: binary_sensor.water_too_high
    style:
      font-size: 1.3em
      left: 11%
      top: 22%
    type: state-icon
  - type: custom:hui-element
    card_type: sensor
    detail: 2
    entity: sensor.pool_temperature
    graph: line
    card_mod:
      style: |
        ha-card {
          --ha-card-background: "rgba(0, 0, 0, 0.3)";
          box-shadow: none;
          color: var(--primary-color);
          .name {display:none}
        }
    style:
      left: 58%
      top: 29%
image: /local/images/pool-pictogram4.png
title: Pool
type: picture-elements

```
This gives me this result:
![image](https://user-images.githubusercontent.com/13660621/127473311-d56efcfe-d830-4c73-bb7c-1fd64b3148e5.png)
It's close, but I want the title of the sensor card and the icon gone, as well as the shadow below the graph. but I guess that is not a task for this card, but for card_mod :-)
