### ISSUE TITLE
Card undefined error

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-hui-element#9]
using

```
      - type: custom:hui-element
        card_type: conditional
        conditions:
          - entity: binary_sensor.xbox_online
            state: 'on'
        card:
          - type: entities
            entities:
              - sensor.xboxid
```

throws this error:
<img width="868" alt="Schermafbeelding 2020-08-12 om 10 14 37" src="https://user-images.githubusercontent.com/33354141/89992057-058b5580-dc85-11ea-8e17-f522054ae805.png">

even if the condition is false (binary_sensor.xbox_online is 'off' )

the binary sensor itself is 'off' when the sensor.xboxid is none, and needed to prevent the yellow 'Entity not available' line in the Lovelace frontend

<img width="419" alt="Schermafbeelding 2020-08-12 om 10 20 47" src="https://user-images.githubusercontent.com/33354141/89992609-c9a4c000-dc85-11ea-8260-45e018d1b5cf.png">

expected behavior would be that if the condition isn't met, no error would be logged.

posting here as it is happening on the hue-element custom card. If you think this is a Home Assistant core issue, I'll post there.
thanks.

btw, the card does work: nothing is displayed when the entity is none, and if it exists, it shows fine.

**Comment by Mariusthvdb** [comment]
wait, really sorry..
Of course: a user error...

should be:
```
      - type: custom:hui-element
        card_type: conditional
        conditions:
          - entity: binary_sensor.xbox_online
            state: 'on'
        card:
          type: entities
          entities:
            - sensor.xboxid
```
my pardon.
